# fly.toml app configuration file generated for my-gpt-reader on 2023-05-28T11:46:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-slack-ai-bot"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"


[env]
  PORT = "8080"
  OPENAI_API_BASE='https://openkey.cloud/v1'
  OPENAI_BASE_URL='https://openkey.cloud/v1'

[build]
    dockerfile="Dockerfile"

[[mounts]]
  source = "volumes_for_slackbot"
  destination = "/data/myGPTReader"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

[[vm]]
  memory = "512mb"

